blog/user/urls.py
from django.urls import path
from user.views import MainCreateView, RegistrationUserView, NotesUserView, AddNotesUserView, LoginUserView, LogoutView

app_name = 'user'

urlpatterns = [
    path('', MainCreateView.as_view(), name='home'),
    path('registration/', RegistrationUserView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login_user'),
    path('note/', NotesUserView.as_view(), name='notes_user'),
    path('add_note/', AddNotesUserView.as_view(), name='add_note'),
    path('logout/', LogoutView.as_view(), name='logout_user'),

]

blog/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Note(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'

blog/user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from user.models import User, Note


class RegisterFormView(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Username:'
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'First_name:'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Last_name:'
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Email:'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Password:'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Confirm Password:'
    }))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class NoteForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Введите вашу заметку...'})
    )

    class Meta:
        model = Note
        fields = ('content',)


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User  # Исправлено на User
        fields = ('username', 'password')

blog/user/views.py
from django.contrib import auth
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from user.forms import RegisterFormView, NoteForm
from user.models import Note
from user.forms import UserLoginForm


class MainCreateView(View):
    template_name = 'user/main.html'
    template_name2 = 'user/notes.html'

    #  Проверка на авторизацию и в зависимости от этого вывод той или иной страницы
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, self.template_name2)
        else:
            # Пользователь не аутентифицирован
            return render(request, self.template_name)


class RegistrationUserView(View):
    template_name = 'user/register_user.html'

    def get(self, request, *args, **kwargs):
        form = RegisterFormView()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = RegisterFormView(request.POST)
        if form.is_valid():
            user = form.save()
            #username = form.cleaned_data['username'] получения любого поля с формы
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('user:notes_user'))
        else:
            print(form.errors)

        return render(request, self.template_name, {'form': form})


class NotesUserView(View):
    template_name = 'user/notes.html'

    def get(self, request):
        notes = Note.objects.filter(user=request.user)
        return render(request, self.template_name, {'result_notes_get': notes})


class AddNotesUserView(View):
    template_name = 'user/add_note.html'

    def get(self, request, *args, **kwargs):
        form = NoteForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()  # Теперь сохраняем измененный объект note в базе данных
            return HttpResponseRedirect(reverse('user:notes_user'))
        else:
            return render(request, 'add_note.html', {'form': form})


class LoginUserView(View):
    template_name = 'user/login_user.html'
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            print(request.user.is_authenticated)
            if user:
                #auth.login(request, user)
                login(request, user)
                return HttpResponseRedirect(reverse('user:notes_user'))
        context = {'form': form}
        return render(request, self.template_name, context)


class LogoutView(View):
    def get(self, request):
        print('hi')
        logout(request)
        return redirect('user:home')

blog/user/templates/user/add_note.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/add_note.css/' %}">
    <title>Добавить заметку</title>
</head>
<body>
    <h1>Добавить заметку</h1>

    <div class="add-note-form">
        <form method="post" action="{% url 'user:add_note' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.content.errors }}
            {{ form.content }}
            <button type="submit" class="add-note-btn">Добавить</button>
            <a href="{% url 'user:logout_user' %}" style="background-color: #007BFF; color: #fff; padding: 10px 20px; border-radius: 5px; cursor: pointer; text-decoration: none;">
            Выйти
            </a>
        </form>
    </div>

</body>
</html>

blog/user/templates/user/login_user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/login.css' %}">
    <title>Авторизация</title>
</head>
<body>
    <div class="login-container">
    <h1>Авторизация</h1>
    <form action="{% url 'user:login_user'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
            {{ form.password }}
        </div>
        <button type="submit">Войти</button>
    </form>
</div>


    <script>
        function login() {
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;



            alert('Вы вошли как: ' + username);

        }
    </script>

</body>
</html>

blog/user/templates/user/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/main.css/' %}"> <!-- Замените путем к вашему CSS-файлу -->
    <title>Registration Page</title>
</head>
<body>
    <div class="container">
        <h1>Welcome to Our Site</h1>
        <p>Register now to get started!</p>
        <a href="{% url 'user:register' %}" class="btn btn-primary">Register</a> <!-- Замените 'registration' на ваш путь к регистрации -->
        <a href="{% url 'user:login_user' %}" class="btn btn-primary">Authorization</a>
    </div>
</body>
</html>

blog/user/templates/user/notes.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/notes.css' %}">
    <title>Заметки пользователя</title>
</head>
<body>
    <h1>Заметки пользователя</h1>

    {% for note in result_notes_get %}
    <div class="note">
        <p>{{ note.content }}</p>
    </div>
    {% endfor %}

    <a href="{% url 'user:add_note' %}" style="background-color: #007BFF; color: #fff; padding: 10px 20px; border-radius: 5px; cursor: pointer; text-decoration: none;">
    Добавить запись
    </a>
    <a href="{% url 'user:logout_user'%}" style="background-color: #007BFF; color: #fff; padding: 10px 20px; border-radius: 5px; cursor: pointer; text-decoration: none;">
        Выход
    </a>
    <!-- Дополнительные заметки будут добавлены динамически -->

</body>
</html>

blog/user/templates/user/register_user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/register.css/' %}"> <!-- Замените путем к вашему CSS-файлу -->
    <title>Registration Page</title>
</head>
<body>
    <div class="container">
        <h1>Register</h1>
        <form action="{% url 'user:register' %}" method="post"> <!-- Замените 'register_user' на ваш путь к обработчику регистрации -->
            {% csrf_token %}

            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}

            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.first_name }}

            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.last_name }}

            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }}

            <label for="{{ form.password1.id_for_label }}">Password:</label>
            {{ form.password1 }}

            <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
            {{ form.password2 }}

            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</body>
</html>